name: xRI
channels:
  - defaults
dependencies:
  - python=3.8
  - aiohttp
  - pytest
  - flake8
  - pip
  - pip:
      - python-dotenv
      - transformers
<<<<<<< HEAD
      - torch
=======
      - torch
>>>>>>> 1baaa87d33ba0a9ec8b45e4fa0e0931183101540
