name: xRI
channels:
  - defaults
dependencies:
  - python=3.8
  - aiohttp
  - pytest  # Ensure pytest is included here
  - flake8  # Ensure flake8 is included here
  - pip:
      - python-dotenv
      - llama2==0.0.1.dev0
