name: xRI
channels:
  - defaults
dependencies:
  - python=3.10
  - aiohttp
  - sqlite
  - dotenv
  - pip
  - pip:
      - llama  # このライブラリがPyPIで利用可能であれば
      - asyncio
      - logging
      - random
