name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install Conda dependencies
      run: |
        conda env create -f environment.yml
        echo "conda activate xRI" >> $GITHUB_ENV

    - name: Install Pip dependencies if requirements.txt exists
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    - name: Lint with flake8
      run: |
        conda run -n xRI flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        conda run -n xRI flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests with pytest
      run: |
        conda run -n xRI pytest test/test_example.py
