name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Update Conda
      run: |
        conda update -n base -c defaults conda -y

    - name: Install Mamba
      run: |
        conda install mamba -n base -c conda-forge

    - name: Install Conda dependencies with Mamba
      run: |
        mamba env update --file environment.yml --name base

    - name: Check for requirements.txt and install Pip dependencies
      run: |
        if [ -f requirements.txt ]; then
          echo "requirements.txt exists. Installing dependencies..."
          pip install -r requirements.txt
        else
          echo "requirements.txt does not exist. Skipping pip install."
        fi

    - name: Lint with flake8
      run: |
        conda install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Install pytest
      run: |
        conda install pytest

    # 更新されたテストの実行部分
    - name: Run tests with pytest
      run: |
        pytest test_example.py
