name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: xRI
        environment-file: environment.yml
        python-version: 3.12.2
        auto-activate-base: false

    # このステップはrequirements.txtに依存する代わりにenvironment.ymlを使用しているため削除されました
    # Flake8はenvironment.ymlに含まれているため、このインストールステップも不要になります

    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        conda run -n xRI flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        conda run -n xRI flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests with pytest
      shell: bash -l {0}
      run: |
        conda run -n xRI pytest test/test_example.py
